# Standardizing all image features 

In [1]:
import image_all_features as iaf
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np

In [3]:
valid_path, features, feature_list = iaf.img_get_feature("../00_data/00_test_pic/")

File ../00_data/00_test_pic//.DS_Store is not readable.
File ../00_data/00_test_pic//.DS_Store is not readable.


In [4]:
valid_path

[['../00_data/00_test_pic//frog_2.jpg'],
 ['../00_data/00_test_pic//test.jpg'],
 ['../00_data/00_test_pic//red.jpg']]

In [5]:
features

['H', 'S', 'V', 'colorfulness', 'contrast', 'R', 'G', 'B']

In [6]:
feature_list

[[49.7562,
  154.8772,
  135.9965,
  50.704544146258954,
  37.9766408829949,
  47.69255702280436,
  93.47851140454452,
  35.24105642257423],
 [53.5365,
  12.9889,
  178.8828,
  6.923195255127685,
  87.36233917303912,
  250.01762699018497,
  250.01766489769238,
  250.0460576194406],
 [171.2669,
  209.4558,
  111.5541,
  60.78603025652514,
  12.412051788676655,
  109.90856701826604,
  17.24466169282189,
  26.167790069462175]]

In [7]:
df = feature_list.copy()
df = pd.DataFrame(df)

In [8]:
df

0         1         2          3          4           5           6  \
0   49.7562  154.8772  135.9965  50.704544  37.976641   47.692557   93.478511   
1   53.5365   12.9889  178.8828   6.923195  87.362339  250.017627  250.017665   
2  171.2669  209.4558  111.5541  60.786030  12.412052  109.908567   17.244662   

            7  
0   35.241056  
1  250.046058  
2   26.167790

In [9]:
# df incl only all numerical columns: 
num_df = df.iloc[:,1:]

In [10]:
num_np = np.array(num_df)

In [11]:
scaler = StandardScaler()
scaled_fit = scaler.fit(num_df)
scaled_fit.transform(num_df)

array([[ 0.35146612, -0.22092354,  0.4804643 , -0.25524185, -1.04214006,
        -0.27625966, -0.66280644],
       [-1.36205244,  1.32017024, -1.39212865,  1.33225311,  1.34899398,
         1.33927947,  1.41330697],
       [ 1.01058632, -1.0992467 ,  0.91166435, -1.07701126, -0.30685392,
        -1.06301981, -0.75050053]])

In [12]:
# the numpy approach gets the same results as the panda approach. Keep everything in np to make it faster. 
scaler_np = StandardScaler()
scaled_fit_np = scaler_np.fit(num_np)
scaled_fit_np.transform(num_np)

array([[ 0.35146612, -0.22092354,  0.4804643 , -0.25524185, -1.04214006,
        -0.27625966, -0.66280644],
       [-1.36205244,  1.32017024, -1.39212865,  1.33225311,  1.34899398,
         1.33927947,  1.41330697],
       [ 1.01058632, -1.0992467 ,  0.91166435, -1.07701126, -0.30685392,
        -1.06301981, -0.75050053]])

In [20]:
def scale_feature(feature_list):
    
    scaler = StandardScaler()
    scaled_fit = scaler.fit(feature_list)
    scaled_feature_list = scaled_fit.transform(feature_list)
    
    return scaled_feature_list
    

In [21]:
scale_feature(feature_list)

array([[-0.740349  ,  0.35146612, -0.22092354,  0.4804643 , -0.25524185,
        -1.04214006, -0.27625966, -0.66280644],
       [-0.67333521, -1.36205244,  1.32017024, -1.39212865,  1.33225311,
         1.34899398,  1.33927947,  1.41330697],
       [ 1.41368421,  1.01058632, -1.0992467 ,  0.91166435, -1.07701126,
        -0.30685392, -1.06301981, -0.75050053]])